/**
 * generate-install-links.ts
 * -------------------------------------------------------------------------
 * Emits the copy-paste-ready "App install links" block into the go-to-market
 * doc (josh-approved-docs/strategy/gtm.md) from the SAME app data the website
 * renders. Every app in src/data/apps.ts gets a smart install link of the form
 *
 *     https://joshapproved.com/apps/<slug>?install=1
 *
 * The link itself always exists (it's just the canonical app page + a param),
 * and the per-app page does device detection + the empty-store guard at
 * runtime. So this list stays correct as new apps are added and as stores go
 * live — re-run after a store sync to refresh the "currently routes to" column.
 *
 * Usage:  npx tsx scripts/generate-install-links.ts [path/to/gtm.md]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { APPS } from '../src/data/apps.ts';

const here = dirname(fileURLToPath(import.meta.url));
const target =
  process.argv[2] ??
  resolve(here, '../../josh-approved-docs/strategy/gtm.md');

const SITE = 'https://joshapproved.com';
const START = '<!-- INSTALL-LINKS:START (auto-generated by joshapproved-web/scripts/generate-install-links.ts — do not edit by hand) -->';
const END = '<!-- INSTALL-LINKS:END -->';

function routesTo(a: (typeof APPS)[number]): string {
  const ios = Boolean(a.appStoreUrl);
  const android = Boolean(a.playStoreUrl);
  const web = Boolean(a.webStoreUrl);
  if (ios && android) return 'App Store + Google Play';
  if (ios) return 'App Store _(Google Play not live yet)_';
  if (android) return 'Google Play _(App Store not live yet)_';
  if (web) return 'Browser extension store';
  return 'No store live yet — the link shows the app page (safe, never a dead listing)';
}

const order: Record<string, number> = { shipped: 0, 'in-progress': 1, planned: 2 };
const rows = [...APPS]
  .sort((a, b) => (order[a.status] ?? 9) - (order[b.status] ?? 9) || a.name.localeCompare(b.name))
  .map((a) => {
    const url = `${SITE}/apps/${a.slug}?install=1`;
    return `| ${a.name} | \`${url}\` | ${routesTo(a)} |`;
  })
  .join('\n');

const block = `${START}
<!-- Regenerate with: cd joshapproved-web && npx tsx scripts/generate-install-links.ts -->

One link per app. Hand it out anywhere — posters, social bios, QR codes, email.
It detects the visitor's device and sends iPhone users to the App Store and
Android users to Google Play (opening the store app directly, so the Josh
Approved page stays in their tab); desktop and everything ambiguous gets a modal
with a QR code + store buttons. A store button only ever appears when that store
is genuinely live, so a customer is never sent to an empty/unapproved listing.

| App | Install link | Currently routes to |
| --- | --- | --- |
${rows}

_Auto-generated from \`joshapproved-web/src/data/apps.ts\`. New apps and newly
live stores appear here on the next regeneration — the links themselves work the
moment an app's page is live._
${END}`;

let doc = readFileSync(target, 'utf8');

if (doc.includes(START) && doc.includes(END)) {
  doc = doc.replace(new RegExp(`${escapeRe(START)}[\\s\\S]*?${escapeRe(END)}`), block);
} else {
  const heading = '\n## App install links (copy-paste for collateral)\n\n';
  doc = doc.replace(/\s*$/, '\n') + heading + block + '\n';
}

writeFileSync(target, doc);
console.log(`Wrote install-links block (${APPS.length} apps) → ${target}`);

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
