// AUTO-GENERATED by josh-approved-factory/scripts/sync-web-store-status.mjs. Do not edit by hand.
// Live App Store + Google Play availability, overlaid onto the catalog in apps.ts.
export type StoreAvailability = {
  status?: 'shipped' | 'in-progress' | 'planned';
  appStoreUrl?: string;
  playStoreUrl?: string;
  iosVersion?: string;
  androidVersion?: string;
};

export const STORE_AVAILABILITY_GENERATED_AT = "2026-06-30T12:11:50.862Z";

export const STORE_AVAILABILITY: Record<string, StoreAvailability> = {
  "free-workout-timer": {"status":"shipped","appStoreUrl":"https://apps.apple.com/us/app/id6767314178","iosVersion":"1.1","playStoreUrl":"https://play.google.com/store/apps/details?id=com.joshapproved.freeworkouttimer","androidVersion":"6 (1.1.2)"},
  "grocery-list": {"status":"shipped","appStoreUrl":"https://apps.apple.com/us/app/id6779417031","iosVersion":"1.0","playStoreUrl":"https://play.google.com/store/apps/details?id=com.joshapproved.grocerylist","androidVersion":"1.0.3"},
  "packing-list": {"status":"shipped","appStoreUrl":"https://apps.apple.com/us/app/id6770051644","iosVersion":"1.0","playStoreUrl":"https://play.google.com/store/apps/details?id=com.joshapproved.packinglist","androidVersion":"1.0.1"},
};
